# Define dependancies version
%global             pjsip_version   2.10
%global             jansson_version 2.12

# Define build variables
%global             optflags        %{optflags} -DLUA_COMPAT_MODULE -fPIC -Ofast
%global             ldflags         -m%{__isa_bits} -Wl,--as-needed,--library-path=%{_libdir} %{__global_ldflags}
%global             astvarrundir    /run/asterisk
%global             tmpbuildroot    /tmp/%{NAME}-%{VERSION}-%{RELEASE}.x86_64
%global             tmpfilesd       1
%global             makeargs        DEBUG= OPTIMIZE= DESTDIR=%{tmpbuildroot} ASTVARRUNDIR=%{astvarrundir} ASTDATADIR=%{_datadir}/asterisk ASTVARLIBDIR=%{_datadir}/asterisk ASTDBDIR=%{_localstatedir}/spool/asterisk NOISY_BUILD=1

# Packages list to build (asterisk-*)
%global             apidoc          0
%global             corosync        0
%global             gmime           0
%global             ices            0
%global             imap            0
%global             jack            0
%global             ldap            0
%global             meetme          0
%global             misdn           0
%global             mysql           0
%global             odbc            0
%global             ooh323          0
%global             phone           0
%global             postgresql      0
%global             radius          0
%global             snmp            0
%global             xmpp            0



Name:               asterisk
Version:            18.12.1
Release:            1.ives%{?dist}

Summary:            The Open Source PBX.

Vendor:             Asterisk
License:            GPLv2
URL:                http://www.asterisk.org/
Packager:           IVèS, Interactivité Vidéo et Systèmes

BuildArchitectures: x86_64

# Requirement used by enabled options in menuselect
BuildRequires:      mariadb-devel
# Requirement used during unit tests
BuildRequires:      ccache

# Asterisk now builds against a bundled copy of pjproject, as they apply some patches
# directly to pjproject before the build against it
Provides:           bundled(pjproject) = %{pjsip_version}

# Requirement used by Asterisk to work in a run environment
Requires:           logrotate



############################################################
#   Source files                                           #
############################################################
Source0:            http://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-%{version}.tar.gz

# Bundling jansson because the version in AlmaLinux is too old
Source1:            http://www.digip.org/jansson/releases/jansson-%{jansson_version}.tar.bz2

# Fix Makefile to install phoneprov samples
# Cannot be a Patch as the Makefile is generated by ./configure
Source2:            ives_fix_makefile.patch

Source3:            asterisk-logrotate
Source4:            asterisk-service
Source5:            asterisk-tmpfiles

############################################################
#   Patch files                                            #
############################################################
#
# An official (from Asterisk/Digium/Sangoma) patch starts with offi_*
# A community (Fedora, EPEL, CentOS, ...) patch starts with commu_*
# An IVèS patch starts with ives_*
#
# On AlmaLinux 8, 'python' command does not exist except for python 2
Patch0:             ives_asterisk-18.12.1-explicit-python3.patch

# Fix MySQL header path (due to change in mariadb-devel package)
Patch1:             commu_asterisk-mariadb.patch

# On AlmaLinux 8, we need mariab-devel instead of mysql-devel
Patch2:             ives_mysql-devel_to_mariadb-devel.patch



%description
Asterisk is a complete PBX in software. It runs on Linux and provides
all of the features you would expect from a PBX and more. Asterisk
does voice over IP in three protocols, and can interoperate with
almost all standards-based telephony equipment using relatively
inexpensive hardware.



############################################################
#   prep Directive -- Unpack archives and apply patches.   #
############################################################
#
# The prep scriptlet is executed first during a build, the scriptlet normally prepares the contents of a source package for building,
# usually by unpacking archives and applying patches.
# The scriptlet can contain any valid sh commands.
#
# At that point, it is the responsibility of the prep script to:
#     - Create the top-level build directory.
#     - Unpack the original sources into the build directory.
#     - Apply patches to the sources, if necessary.
#     - Perform any other actions required to get the sources in a ready-to-build state.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-PREP-SCRIPT
#
%prep
%setup -q
%patch0 -p1
%patch1 -p1
%patch2 -p1
/bin/sh contrib/scripts/install_prereq install
/bin/sh contrib/scripts/get_mp3_source.sh
/bin/sh bootstrap.sh



###########################################################################
#   build Directive -- Configure and compile components to be packaged.   #
###########################################################################
#
# The build scriptlet is the second scriptlet executed during a build, immediately after prep.
# The scriptlet normally builds the components to be included in a binary package, usually by configuring and compiling source code
# from the previously unpacked and patched archives.
# The scriptlet can contain any valid sh commands.
#
# The build script is usually the command make, maybe a configuration script, and little else.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-BUILD-SCRIPT
#
%build
export CFLAGS="%{optflags}"
export CXXFLAGS="%{optflags}"
export FFLAGS="%{optflags}"
export LDFLAGS="%{ldflags}"
export ASTCFLAGS=" "
./configure --prefix=/usr --libdir=%{_libdir} --with-pjproject-bundled
make %{makeargs}
make menuselect.makeopts %{makeargs}
# Enable Add-ons used by IVèS
menuselect/menuselect --enable chan_mobile --enable chan_ooh323 --enable format_mp3 --enable res_config_mysql menuselect.makeopts
# Disable deprecated applications
menuselect/menuselect --disable app_adsiprog --disable app_getcpeid --disable app_ices --disable app_image --disable app_nbscat --disable app_url menuselect.makeopts
# Disable deprecated channel drivers
menuselect/menuselect --disable chan_oss --disable chan_sip menuselect.makeopts
# Enable codec translators used by IVèS
menuselect/menuselect --enable codec_opus --enable codec_silk --enable codec_siren7 --enable codec_siren14 menuselect.makeopts
# Disable deprecated resource modules
menuselect/menuselect --disable res_adsi --disable res_monitor menuselect.makeopts
# Enable resource modules used by IVèS
menuselect/menuselect --enable res_chan_stats --enable res_endpoint_stats --enable res_pktccops menuselect.makeopts
# Enable core sound packages used by IVèS
menuselect/menuselect --enable CORE-SOUNDS-EN-SLN16 --enable CORE-SOUNDS-EN-WAV --enable CORE-SOUNDS-EN_AU-SLN16 --enable CORE-SOUNDS-EN_AU-WAV --enable CORE-SOUNDS-EN_GB-SLN16 --enable CORE-SOUNDS-EN_GB-WAV --enable CORE-SOUNDS-ES-G722 --enable CORE-SOUNDS-ES-SLN16 --enable CORE-SOUNDS-ES-WAV --enable CORE-SOUNDS-FR-SLN16 --enable CORE-SOUNDS-FR-WAV --enable CORE-SOUNDS-IT-SLN16 --enable CORE-SOUNDS-IT-WAV --enable CORE-SOUNDS-JA-SLN16 --enable CORE-SOUNDS-JA-WAV --enable CORE-SOUNDS-RU-SLN16 --enable CORE-SOUNDS-RU-WAV --enable CORE-SOUNDS-SV-SLN16 --enable CORE-SOUNDS-SV-WAV menuselect.makeopts
# Enable music on hold file packages used by IVèS
menuselect/menuselect --enable MOH-OPSOUND-SLN16 --enable MOH-OPSOUND-WAV menuselect.makeopts
# Enable extras sound packages used by IVèS
menuselect/menuselect --enable EXTRA-SOUNDS-EN-SLN16 --enable EXTRA-SOUNDS-EN-WAV --enable EXTRA-SOUNDS-EN_GB-SLN16 --enable EXTRA-SOUNDS-EN_GB-WAV --enable EXTRA-SOUNDS-FR-SLN16 --enable EXTRA-SOUNDS-FR-WAV menuselect.makeopts
# Compiler flags
menuselect/menuselect --enable DONT_OPTIMIZE --disable BUILD_NATIVE menuselect.makeopts
make install %{makeargs}
make samples %{makeargs}
%{__patch} -p 1 -N -i %{SOURCE2} || true
make config %{makeargs}
%{__rm} -f debug*.list



###############################################################
#   install Directive -- Install components to be packaged.   #
###############################################################
#
# The install scriptlet is the third scriptlet executed during a build, immediately after build.
# The scriptlet normally installs components to be included in a binary package, usually by copying files from the build directory
# tree to an install directory tree.
# The scriptlet can contain any valid sh commands.
#
# As the name implies, it is this script's responsibility to do whatever is necessary to actually install the newly built software.
# In most cases, this means a single make install command, or a few commands to copy files and create directories.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-INSTALL-SCRIPT
#
%install
%{__install} -D -m 0644 -d %{buildroot}/etc/asterisk/
%{__install} -D -p -m 0644 %{tmpbuildroot}/etc/asterisk/* %{buildroot}/etc/asterisk/

%{__install} -D -m 0644 -d %{buildroot}/etc/logrotate.d/
%{__install} -D -p -m 0644 %{SOURCE3} ${RPM_BUILD_ROOT}/etc/logrotate.d/

%{__install} -D -m 0644 -d %{buildroot}/run/asterisk/

%{__install} -D -m 0644 -d %{buildroot}/usr/lib/systemd/system/
%{__install} -D -p -m 0644 %{SOURCE4} ${RPM_BUILD_ROOT}/usr/lib/systemd/system/asterisk.service

%{__install} -D -m 0644 -d %{buildroot}/usr/lib/tmpfiles.d/
%{__install} -D -p -m 0644 %{SOURCE5} ${RPM_BUILD_ROOT}/usr/lib/tmpfiles.d/asterisk.conf

%{__install} -D -m 0644 -d %{buildroot}/usr/lib64/asterisk/modules/
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/lib64/asterisk/modules/* %{buildroot}/usr/lib64/asterisk/modules/
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/lib64/libasteriskpj.so %{buildroot}/usr/lib64/libasteriskpj.so
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/lib64/libasteriskpj.so.2 %{buildroot}/usr/lib64/libasteriskpj.so.2
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/lib64/libasteriskssl.so %{buildroot}/usr/lib64/libasteriskssl.so
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/lib64/libasteriskssl.so.1 %{buildroot}/usr/lib64/libasteriskssl.so.1

%{__install} -D -m 0644 -d %{buildroot}/usr/sbin/
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/sbin/* %{buildroot}/usr/sbin/

%{__install} -D -m 0644 -d %{buildroot}/usr/share/man/man8/
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/astdb2bdb.8 %{buildroot}/usr/share/man/man8/astdb2bdb.8
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/astdb2sqlite3.8 %{buildroot}/usr/share/man/man8/astdb2sqlite3.8
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/asterisk.8 %{buildroot}/usr/share/man/man8/asterisk.8
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/astgenkey.8 %{buildroot}/usr/share/man/man8/astgenkey.8
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/autosupport.8 %{buildroot}/usr/share/man/man8/autosupport.8
%{__install} -D -p -m 0644 %{tmpbuildroot}/usr/share/man/man8/safe_asterisk.8 %{buildroot}/usr/share/man/man8/safe_asterisk.8



##############################################
#   check Directive -- Run included tests.   #
##############################################
#
# The check scriptlet is the fourth scriptlet executed during a build, immediately after install.
# The scriptlet normally runs the test suite for the built components if one is available.
# The scriptlet can contain any valid sh commands.
#
# This script's primary function is to run the test suite of the built software to ensure that the binaries work correctly.
# Some typical commands to run in this script are make test or make check.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-CHECK-SCRIPT
#
%check



###################################################
#   clean Directive -- Remove build components.   #
###################################################
#
# The clean scriptlet is executed at the end of a build.
# The scriptlet cleans up files produced during a build, usually by removing the install directory tree.
# The scriptlet can contain any valid sh commands.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-CLEAN-SCRIPT
#
%clean



##################################
#   Install/Erase-time Scripts   #
##################################
#
# Scriplets values:
#   If you need to know if you are unstalling, upgrading or uninstalling a package,
#   use the following table to know which value has $1 in which case.
#
#                +---------+---------+-----------+
#                | install | upgrade | uninstall |
#    +-----------+---------+---------+-----------+
#    | pretrans  | $1 == 1 | $1 == 2 |     NA    |
#    +-----------+---------+---------+-----------+
#    | pre       | $1 == 1 | $1 == 2 |     NA    |
#    +-----------+---------+---------+-----------+
#    | post      | $1 == 1 | $1 == 2 |     NA    |
#    +-----------+---------+---------+-----------+
#    | preun     |    NA   | $1 == 1 |  $1 == 0  |
#    +-----------+---------+---------+-----------+
#    | postun    |    NA   | $1 == 1 |  $1 == 0  |
#    +-----------+---------+---------+-----------+
#    | posttrans | $1 == 1 | $1 == 1 |     NA    |
#    +-----------+---------+---------+-----------+
#
# SOURCE: https://www.golinuxhub.com/2018/05/how-to-execute-script-at-pre-post-preun-postun-spec-file-rpm/
#
# Other scriptlet exists:
#      https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax
#      https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering



#####################################################################
#   pretrans Directive -- Before anything at all has been installed #
#####################################################################
#
# Note that the %pretrans scriptlet will, in the particular case of system installation,
# run before anything at all has been installed. This implies that it cannot have any
# dependencies at all. For this reason, %pretrans is best avoided.
#
# SOURCE: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#pretrans
%pretrans



######################################################
#   pre Directive -- Before installing the package   #
######################################################
#
# The pre script is run just before the package is installed.
# It is the rare package that requires anything to be done prior to installation;
# none of the 350 packages that comprise Red Hat Linux 4.0 make use of it.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-PRE-SCRIPT
#
%pre



######################################################
#   post Directive -- After installing the package   #
######################################################
#
# The post script executes after the package has been installed.
#
# One of the most popular reasons a post script is needed is to run ldconfig
# to update the list of available shared libraries after a new one has been installed.
# Of course, other functions can be performed in a post script.
# For example, packages that install shells use the post script to add the shell name to /etc/shells.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S4-RPM-INSIDE-POST-SCRIPT
#
%post



##########################################################
#   preun Directive -- Before uninstalling the package   #
##########################################################
#
# If there's a time when your package needs to have one last look around before the user erases it,
# the place to do it is in the preun script. Anything that a package needs to do immediately prior
# to RPM taking any action to erase the package, can be done here.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-PREUN-SCRIPT
#
%preun



##########################################################
#   postun Directive -- After uninstalling the package   #
##########################################################
#
# The postun script executes after the package has been removed.
# It is the last chance for a package to clean up after itself.
#
# Quite often, postun scripts are used to run ldconfig to remove newly erased shared libraries from ld.so.cache.
#
# SOURCE: http://ftp.rpm.org/max-rpm/s1-rpm-inside-scripts.html#S3-RPM-INSIDE-POSTUN-SCRIPT
#
%postun



%files
# Need to sort files, some of them are not from asterisk package but from asterisk-* packages.
/etc/asterisk/*
/usr/lib64/asterisk/modules/*
/usr/lib64/libasteriskpj.so
/usr/lib64/libasteriskpj.so.2
/usr/lib64/libasteriskssl.so
/usr/lib64/libasteriskssl.so.1
/usr/sbin/astcanary
/usr/sbin/astdb2bdb
/usr/sbin/astdb2sqlite3
/usr/sbin/asterisk
/usr/sbin/astgenkey
/usr/sbin/astversion
/usr/sbin/autosupport
/usr/sbin/rasterisk
/usr/sbin/safe_asterisk

###########################
##### asterisk-apidoc #####
###########################

#############################
##### asterisk-corosync #####
#############################

##########################
##### asterisk-gmime #####
##########################

#########################
##### asterisk-ices #####
#########################

#########################
##### asterisk-imap #####
#########################

#########################
##### asterisk-jack #####
#########################

#########################
##### asterisk-ldap #####
#########################

###########################
##### asterisk-meetme #####
###########################

##########################
##### asterisk-misdn #####
##########################

##########################
##### asterisk-mysql #####
##########################

#########################
##### asterisk-odbc #####
#########################

###########################
##### asterisk-ooh323 #####
###########################

##########################
##### asterisk-phone #####
##########################

###############################
##### asterisk-postgresql #####
###############################

###########################
##### asterisk-radius #####
###########################

#########################
##### asterisk-snmp #####
#########################

#########################
##### asterisk-xmpp #####
#########################

